/**
 * 100-Agent Mega Config — Part 5: WHO (W01-W05) + FDA (A01-A05) + Agriculture (G01-G10) + GACP Expert (E01-E10)
 */
module.exports = [
  // ═══ WHO STANDARDS (W01-W05) ═══
  {key:'W01',name:'GACP Guidelines WHO',icon:'🌍',cat:'WHO',steps:[
    {name:'Standards verify',path:'/standards'},{name:'Categories WHO',path:'/cultivation-config/gacp-categories'},
    {name:'Methods WHO',path:'/cultivation-config/cultivation-methods'},
    {name:'Soils WHO',path:'/cultivation-config/soil-types'},
    {name:'Plants WHO',path:'/plants'},{name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Step 4 WHO',path:'/cultivation-config/step-requirements/4'},
    {name:'Step 5 WHO',path:'/cultivation-config/step-requirements/5'},
    {name:'Document slots',path:'/config/document-slots'},
    {name:'Pricing',path:'/pricing/fees'},{name:'Locations',path:'/master-data/locations'},
    {name:'Health check',path:'/health'},
  ]},
  {key:'W02',name:'Quality Standards WHO',icon:'🌍',cat:'WHO',steps:[
    {name:'Standards',path:'/standards'},{name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Soils',path:'/cultivation-config/soil-types'},
    {name:'Plants',path:'/plants'},{name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Pre-submit QC',method:'POST',path:'/validation/pre-submission',body:{applicantType:'INDIVIDUAL',farmName:'WHO QC test',cultivationMethod:'outdoor',plantCount:200}},
    {name:'Audit trail',path:'/audit'},{name:'Audit stats',path:'/audit/stats'},
    {name:'Master data',path:'/master-data'},{name:'Metrics',path:'/metrics'},
    {name:'Health check',path:'/health'},
  ]},
  {key:'W03',name:'Documentation WHO',icon:'🌍',cat:'WHO',steps:[
    {name:'Document slots',path:'/config/document-slots'},
    {name:'Step 1 docs',path:'/cultivation-config/step-requirements/1'},
    {name:'Step 2 docs',path:'/cultivation-config/step-requirements/2'},
    {name:'Step 3 docs',path:'/cultivation-config/step-requirements/3'},
    {name:'Step 4 docs',path:'/cultivation-config/step-requirements/4'},
    {name:'Step 5 docs',path:'/cultivation-config/step-requirements/5'},
    {name:'Standards',path:'/standards'},{name:'Plants',path:'/plants'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Audit trail',path:'/audit'},{name:'Health check',path:'/health'},
  ]},
  {key:'W04',name:'Traceability WHO',icon:'🌍',cat:'WHO',steps:[
    {name:'Audit trail',path:'/audit'},{name:'Audit stats',path:'/audit/stats'},
    {name:'Standards',path:'/standards'},{name:'Plants',path:'/plants'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Locations',path:'/master-data/locations'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Pricing fees',path:'/pricing/fees'},{name:'Master data',path:'/master-data'},
    {name:'Metrics',path:'/metrics'},{name:'Health check',path:'/health'},
  ]},
  {key:'W05',name:'Safety Standards WHO',icon:'🌍',cat:'WHO',steps:[
    {name:'Standards',path:'/standards'},{name:'Plants',path:'/plants'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Soils safety',path:'/cultivation-config/soil-types'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Pre-submit safety',method:'POST',path:'/validation/pre-submission',body:{applicantType:'ENTERPRISE',farmName:'WHO safety test',cultivationMethod:'greenhouse',plantCount:1000}},
    {name:'Document slots',path:'/config/document-slots'},
    {name:'Audit trail',path:'/audit'},{name:'Locations',path:'/master-data/locations'},
    {name:'Health check',path:'/health'},{name:'Version',path:'/version'},
  ]},
  // ═══ FDA COMPLIANCE (A01-A05) ═══
  {key:'A01',name:'Registration FDA',icon:'💊',cat:'FDA',steps:[
    {name:'Pre-submit FDA',method:'POST',path:'/validation/pre-submission',body:{applicantType:'ENTERPRISE',farmName:'FDA Registration Test',cultivationMethod:'outdoor',plantCount:500}},
    {name:'Standards',path:'/standards'},{name:'Plants',path:'/plants'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Document slots',path:'/config/document-slots'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Locations',path:'/master-data/locations'},{name:'Master data',path:'/master-data'},
    {name:'Pricing',path:'/pricing/fees'},{name:'Audit trail',path:'/audit'},
    {name:'Health check',path:'/health'},
  ]},
  {key:'A02',name:'Labeling Standards FDA',icon:'💊',cat:'FDA',steps:[
    {name:'Standards',path:'/standards'},{name:'Plants',path:'/plants'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Soils',path:'/cultivation-config/soil-types'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Document slots',path:'/config/document-slots'},
    {name:'Locations',path:'/master-data/locations'},
    {name:'Purposes',path:'/master-data/purposes'},
    {name:'Audit trail',path:'/audit'},{name:'Version',path:'/version'},
    {name:'Health check',path:'/health'},
  ]},
  {key:'A03',name:'Quality Control FDA',icon:'💊',cat:'FDA',steps:[
    {name:'Standards QC',path:'/standards'},{name:'Plants QC',path:'/plants'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Soils',path:'/cultivation-config/soil-types'},
    {name:'Step 5 QC',path:'/cultivation-config/step-requirements/5'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Pre-submit QC',method:'POST',path:'/validation/pre-submission',body:{applicantType:'INDIVIDUAL',farmName:'FDA QC test',cultivationMethod:'indoor',plantCount:100}},
    {name:'Audit trail',path:'/audit'},{name:'Audit stats',path:'/audit/stats'},
    {name:'Metrics',path:'/metrics'},{name:'Health check',path:'/health'},
  ]},
  {key:'A04',name:'Safety Assessment FDA',icon:'💊',cat:'FDA',steps:[
    {name:'Standards safety',path:'/standards'},{name:'Plants safety',path:'/plants'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods safety',path:'/cultivation-config/cultivation-methods'},
    {name:'Soils safety',path:'/cultivation-config/soil-types'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Pre-submit safety',method:'POST',path:'/validation/pre-submission',body:{applicantType:'COOPERATIVE',farmName:'FDA safety review',cultivationMethod:'outdoor',plantCount:300}},
    {name:'Document slots',path:'/config/document-slots'},
    {name:'Locations',path:'/master-data/locations'},{name:'Audit trail',path:'/audit'},
    {name:'Master data',path:'/master-data'},{name:'Health check',path:'/health'},
  ]},
  {key:'A05',name:'Post-Market FDA',icon:'💊',cat:'FDA',steps:[
    {name:'Audit trail',path:'/audit'},{name:'Audit stats',path:'/audit/stats'},
    {name:'Standards',path:'/standards'},{name:'Plants',path:'/plants'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Metrics',path:'/metrics'},{name:'Master data',path:'/master-data'},
    {name:'Locations',path:'/master-data/locations'},
    {name:'Pricing',path:'/pricing/fees'},{name:'Version',path:'/version'},
    {name:'Health check',path:'/health'},
  ]},
  // ═══ AGRICULTURE EXPERT (G01-G10) ═══
  {key:'G01',name:'Soil Analysis',icon:'🌿',cat:'Agriculture',steps:[
    {name:'Soil types',path:'/cultivation-config/soil-types'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Standards',path:'/standards'},{name:'Plants',path:'/plants'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Locations',path:'/master-data/locations'},
    {name:'Step 5 soil',path:'/cultivation-config/step-requirements/5'},
    {name:'Pre-submit soil',method:'POST',path:'/validation/pre-submission',body:{applicantType:'INDIVIDUAL',farmName:'วิเคราะห์ดิน test',cultivationMethod:'outdoor',plantCount:100}},
    {name:'Master data',path:'/master-data'},{name:'Audit trail',path:'/audit'},
    {name:'Health check',path:'/health'},
  ]},
  {key:'G02',name:'Cultivation Methods',icon:'🌿',cat:'Agriculture',steps:[
    {name:'Methods list',path:'/cultivation-config/cultivation-methods'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Soils',path:'/cultivation-config/soil-types'},
    {name:'Standards',path:'/standards'},{name:'Plants',path:'/plants'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Calc outdoor',method:'POST',path:'/pricing/calculate',body:{plantCount:100,area:5,cultivationMethod:'outdoor'}},
    {name:'Calc indoor',method:'POST',path:'/pricing/calculate',body:{plantCount:50,area:2,cultivationMethod:'indoor'}},
    {name:'Calc greenhouse',method:'POST',path:'/pricing/calculate',body:{plantCount:200,area:10,cultivationMethod:'greenhouse'}},
    {name:'Locations',path:'/master-data/locations'},
    {name:'Step 5 methods',path:'/cultivation-config/step-requirements/5'},
    {name:'Health check',path:'/health'},
  ]},
  {key:'G03',name:'Plant Species DB',icon:'🌿',cat:'Agriculture',steps:[
    {name:'Plants list',path:'/plants'},{name:'Standards',path:'/standards'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Soils',path:'/cultivation-config/soil-types'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Locations',path:'/master-data/locations'},
    {name:'Master data',path:'/master-data'},
    {name:'Purposes',path:'/master-data/purposes'},
    {name:'Step 5 plants',path:'/cultivation-config/step-requirements/5'},
    {name:'Pricing',path:'/pricing/fees'},{name:'Health check',path:'/health'},
  ]},
  {key:'G04',name:'Growth Cycle',icon:'🌱',cat:'Agriculture',steps:[
    {name:'Plants',path:'/plants'},{name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Soils',path:'/cultivation-config/soil-types'},
    {name:'Standards',path:'/standards'},{name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Step 1',path:'/cultivation-config/step-requirements/1'},
    {name:'Step 5',path:'/cultivation-config/step-requirements/5'},
    {name:'Step 10',path:'/cultivation-config/step-requirements/10'},
    {name:'Locations',path:'/master-data/locations'},
    {name:'Purposes',path:'/master-data/purposes'},{name:'Health check',path:'/health'},
  ]},
  {key:'G05',name:'Pest Management',icon:'🦟',cat:'Agriculture',steps:[
    {name:'Standards',path:'/standards'},{name:'Plants',path:'/plants'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Soils',path:'/cultivation-config/soil-types'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Step 5 pest',path:'/cultivation-config/step-requirements/5'},
    {name:'Step 7 pest',path:'/cultivation-config/step-requirements/7'},
    {name:'Locations',path:'/master-data/locations'},
    {name:'Master data',path:'/master-data'},{name:'Audit trail',path:'/audit'},
    {name:'Health check',path:'/health'},
  ]},
  {key:'G06',name:'Harvest Quality',icon:'🌾',cat:'Agriculture',steps:[
    {name:'Standards',path:'/standards'},{name:'Plants',path:'/plants'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Step 8 harvest',path:'/cultivation-config/step-requirements/8'},
    {name:'Step 9 harvest',path:'/cultivation-config/step-requirements/9'},
    {name:'Soils',path:'/cultivation-config/soil-types'},
    {name:'Locations',path:'/master-data/locations'},
    {name:'Purposes',path:'/master-data/purposes'},
    {name:'Pricing',path:'/pricing/fees'},{name:'Health check',path:'/health'},
  ]},
  {key:'G07',name:'Environmental Monitor',icon:'🌡️',cat:'Agriculture',steps:[
    {name:'Soils env',path:'/cultivation-config/soil-types'},
    {name:'Methods env',path:'/cultivation-config/cultivation-methods'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Standards',path:'/standards'},{name:'Plants',path:'/plants'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Locations env',path:'/master-data/locations'},
    {name:'Step 5 env',path:'/cultivation-config/step-requirements/5'},
    {name:'Step 7 env',path:'/cultivation-config/step-requirements/7'},
    {name:'Master data',path:'/master-data'},{name:'Audit trail',path:'/audit'},
    {name:'Health check',path:'/health'},
  ]},
  {key:'G08',name:'Organic Standards',icon:'♻️',cat:'Agriculture',steps:[
    {name:'Standards organic',path:'/standards'},{name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Soils',path:'/cultivation-config/soil-types'},
    {name:'Plants',path:'/plants'},{name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Pre-submit organic',method:'POST',path:'/validation/pre-submission',body:{applicantType:'INDIVIDUAL',farmName:'เกษตรอินทรีย์ test',cultivationMethod:'outdoor',plantCount:150}},
    {name:'Document slots',path:'/config/document-slots'},
    {name:'Locations',path:'/master-data/locations'},
    {name:'Step 5 org',path:'/cultivation-config/step-requirements/5'},
    {name:'Pricing',path:'/pricing/fees'},{name:'Health check',path:'/health'},
  ]},
  {key:'G09',name:'Irrigation & Water',icon:'💧',cat:'Agriculture',steps:[
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Soils',path:'/cultivation-config/soil-types'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Standards',path:'/standards'},{name:'Plants',path:'/plants'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Step 5 water',path:'/cultivation-config/step-requirements/5'},
    {name:'Step 6 water',path:'/cultivation-config/step-requirements/6'},
    {name:'Locations',path:'/master-data/locations'},
    {name:'Master data',path:'/master-data'},{name:'Audit trail',path:'/audit'},
    {name:'Health check',path:'/health'},
  ]},
  {key:'G10',name:'Post-Harvest Handling',icon:'📦',cat:'Agriculture',steps:[
    {name:'Standards',path:'/standards'},{name:'Plants',path:'/plants'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Step 9 post',path:'/cultivation-config/step-requirements/9'},
    {name:'Step 10 post',path:'/cultivation-config/step-requirements/10'},
    {name:'Step 11 post',path:'/cultivation-config/step-requirements/11'},
    {name:'Soils',path:'/cultivation-config/soil-types'},
    {name:'Locations',path:'/master-data/locations'},
    {name:'Purposes',path:'/master-data/purposes'},{name:'Health check',path:'/health'},
  ]},
  // ═══ GACP EXPERT (E01-E10) ═══
  {key:'E01',name:'Good Agricultural Practices',icon:'📋',cat:'GACP Expert',steps:[
    {name:'Standards GAP',path:'/standards'},{name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Soils',path:'/cultivation-config/soil-types'},
    {name:'Plants',path:'/plants'},{name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Step 4 GAP',path:'/cultivation-config/step-requirements/4'},
    {name:'Step 5 GAP',path:'/cultivation-config/step-requirements/5'},
    {name:'Document slots',path:'/config/document-slots'},
    {name:'Locations',path:'/master-data/locations'},
    {name:'Pricing',path:'/pricing/fees'},{name:'Health check',path:'/health'},
  ]},
  {key:'E02',name:'Good Collection Practices',icon:'📋',cat:'GACP Expert',steps:[
    {name:'Standards GCP',path:'/standards'},{name:'Plants GCP',path:'/plants'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Step 7 GCP',path:'/cultivation-config/step-requirements/7'},
    {name:'Step 8 GCP',path:'/cultivation-config/step-requirements/8'},
    {name:'Step 9 GCP',path:'/cultivation-config/step-requirements/9'},
    {name:'Soils',path:'/cultivation-config/soil-types'},
    {name:'Locations',path:'/master-data/locations'},
    {name:'Master data',path:'/master-data'},{name:'Health check',path:'/health'},
  ]},
  {key:'E03',name:'Quality Assurance System',icon:'✅',cat:'GACP Expert',steps:[
    {name:'Standards QA',path:'/standards'},{name:'Plants',path:'/plants'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Soils',path:'/cultivation-config/soil-types'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Pre-submit QA',method:'POST',path:'/validation/pre-submission',body:{applicantType:'INDIVIDUAL',farmName:'QA system test',cultivationMethod:'outdoor',plantCount:100}},
    {name:'Audit trail',path:'/audit'},{name:'Audit stats',path:'/audit/stats'},
    {name:'Metrics',path:'/metrics'},{name:'Document slots',path:'/config/document-slots'},
    {name:'Health check',path:'/health'},
  ]},
  {key:'E04',name:'Personnel Training',icon:'👨‍🏫',cat:'GACP Expert',steps:[
    {name:'Standards training',path:'/standards'},{name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Step 1 training',path:'/cultivation-config/step-requirements/1'},
    {name:'Step 2 training',path:'/cultivation-config/step-requirements/2'},
    {name:'Step 3 training',path:'/cultivation-config/step-requirements/3'},
    {name:'Plants',path:'/plants'},{name:'Soils',path:'/cultivation-config/soil-types'},
    {name:'Locations',path:'/master-data/locations'},
    {name:'Document slots',path:'/config/document-slots'},{name:'Health check',path:'/health'},
  ]},
  {key:'E05',name:'Facility Standards',icon:'🏭',cat:'GACP Expert',steps:[
    {name:'Standards facility',path:'/standards'},{name:'Plants',path:'/plants'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Soils',path:'/cultivation-config/soil-types'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Step 4 facility',path:'/cultivation-config/step-requirements/4'},
    {name:'Step 5 facility',path:'/cultivation-config/step-requirements/5'},
    {name:'Locations',path:'/master-data/locations'},
    {name:'Document slots',path:'/config/document-slots'},
    {name:'Pricing',path:'/pricing/fees'},{name:'Health check',path:'/health'},
  ]},
  {key:'E06',name:'Equipment Maintenance',icon:'🔧',cat:'GACP Expert',steps:[
    {name:'Standards equip',path:'/standards'},{name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Step 6 equip',path:'/cultivation-config/step-requirements/6'},
    {name:'Step 7 equip',path:'/cultivation-config/step-requirements/7'},
    {name:'Plants',path:'/plants'},{name:'Soils',path:'/cultivation-config/soil-types'},
    {name:'Locations',path:'/master-data/locations'},
    {name:'Master data',path:'/master-data'},{name:'Audit trail',path:'/audit'},
    {name:'Health check',path:'/health'},
  ]},
  {key:'E07',name:'Record Keeping',icon:'📝',cat:'GACP Expert',steps:[
    {name:'Audit trail',path:'/audit'},{name:'Audit stats',path:'/audit/stats'},
    {name:'Standards',path:'/standards'},{name:'Plants',path:'/plants'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Document slots',path:'/config/document-slots'},
    {name:'Step 10 records',path:'/cultivation-config/step-requirements/10'},
    {name:'Step 11 records',path:'/cultivation-config/step-requirements/11'},
    {name:'Locations',path:'/master-data/locations'},
    {name:'Metrics',path:'/metrics'},{name:'Health check',path:'/health'},
  ]},
  {key:'E08',name:'Internal Audit',icon:'🔍',cat:'GACP Expert',steps:[
    {name:'Audit trail',path:'/audit'},{name:'Audit stats',path:'/audit/stats'},
    {name:'Standards audit',path:'/standards'},{name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Metrics',path:'/metrics'},{name:'Plants',path:'/plants'},
    {name:'Document slots',path:'/config/document-slots'},
    {name:'Step 5 audit',path:'/cultivation-config/step-requirements/5'},
    {name:'Locations',path:'/master-data/locations'},{name:'Health check',path:'/health'},
  ]},
  {key:'E09',name:'Corrective Actions',icon:'🔄',cat:'GACP Expert',steps:[
    {name:'Audit trail',path:'/audit'},{name:'Audit stats',path:'/audit/stats'},
    {name:'Standards',path:'/standards'},{name:'Plants',path:'/plants'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Pre-submit',method:'POST',path:'/validation/pre-submission',body:{applicantType:'INDIVIDUAL',farmName:'corrective action',cultivationMethod:'outdoor',plantCount:100}},
    {name:'Document slots',path:'/config/document-slots'},
    {name:'Locations',path:'/master-data/locations'},
    {name:'Metrics',path:'/metrics'},{name:'Health check',path:'/health'},
  ]},
  {key:'E10',name:'Continuous Improvement',icon:'📈',cat:'GACP Expert',steps:[
    {name:'Standards CI',path:'/standards'},{name:'Plants',path:'/plants'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Soils',path:'/cultivation-config/soil-types'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Audit trail',path:'/audit'},{name:'Audit stats',path:'/audit/stats'},
    {name:'Metrics',path:'/metrics'},{name:'Master data',path:'/master-data'},
    {name:'Version',path:'/version'},{name:'Health check',path:'/health'},
  ]},
];
