/**
 * 100-Agent Mega Config — Part 2: Backend (B01-B15)
 */
module.exports = [
  {key:'B01',name:'API Health & Uptime',icon:'⚡',cat:'Backend',steps:[
    {name:'Health check',path:'/health'},{name:'Version',path:'/version'},
    {name:'Metrics',path:'/metrics'},{name:'DB status',path:'/health',field:'dbStatus.status'},
    {name:'Uptime',path:'/health',field:'uptime'},{name:'Standards',path:'/standards'},
    {name:'Plants',path:'/plants'},{name:'Master data',path:'/master-data'},
    {name:'Pricing fees',path:'/pricing/fees'},{name:'Locations',path:'/master-data/locations'},
    {name:'Audit trail',path:'/audit'},{name:'Audit stats',path:'/audit/stats'},
  ]},
  {key:'B02',name:'Auth & Token Validation',icon:'🔒',cat:'Backend',steps:[
    {name:'Invalid token',path:'/dashboard',expect:[401,403]},
    {name:'No auth dashboard',path:'/applications/my',expect:[401,403]},
    {name:'No auth notifs',path:'/notifications',expect:[401,403]},
    {name:'Malformed JWT',path:'/dashboard',expect:[401,403]},
    {name:'Empty bearer',path:'/dashboard',expect:[401,403]},
    {name:'Empty login body',method:'POST',path:'/auth/health/login',body:{},expect:[400,401]},
    {name:'SQL injection',method:'POST',path:'/auth/health/login',body:{identifier:"' OR 1=1 --",password:"x"},expect:[400,401]},
    {name:'XSS attempt',path:'/standards?q=<script>alert(1)</script>'},
    {name:'Path traversal',path:'/documents/../../../etc/passwd',expect:[400,401,403,404]},
    {name:'Long string',method:'POST',path:'/auth/health/login',body:{identifier:'A'.repeat(5000),password:'x'},expect:[400,401,413]},
    {name:'Unicode injection',method:'POST',path:'/auth/health/login',body:{identifier:'🔥ทดสอบ',password:'x'},expect:[400,401]},
    {name:'404 unknown route',path:'/nonexistent-route',expect:[404]},
  ]},
  {key:'B03',name:'RESTful API Standards',icon:'📡',cat:'Backend',steps:[
    {name:'GET /health',path:'/health'},{name:'GET /version',path:'/version'},
    {name:'GET /standards',path:'/standards'},{name:'GET /plants',path:'/plants'},
    {name:'GET /master-data',path:'/master-data'},{name:'GET /pricing/fees',path:'/pricing/fees'},
    {name:'POST calculate',method:'POST',path:'/pricing/calculate',body:{plantCount:100,area:5,cultivationMethod:'outdoor'}},
    {name:'GET locations',path:'/master-data/locations'},{name:'GET fees',path:'/master-data/fees'},
    {name:'GET qr-pricing',path:'/master-data/qr-pricing'},
    {name:'GET audit',path:'/audit'},{name:'GET metrics',path:'/metrics'},
  ]},
  {key:'B04',name:'Error Response Format',icon:'⚠️',cat:'Backend',steps:[
    {name:'400 empty login',method:'POST',path:'/auth/health/login',body:{},expect:[400,401]},
    {name:'400 empty register',method:'POST',path:'/auth/health/register',body:{},expect:[400,422]},
    {name:'401 no token',path:'/dashboard',expect:[401,403]},
    {name:'401 bad token',path:'/dashboard',expect:[401,403]},
    {name:'404 unknown',path:'/not-found-route',expect:[404]},
    {name:'Pre-submit valid',method:'POST',path:'/validation/pre-submission',body:{applicantType:'INDIVIDUAL',farmName:'test',cultivationMethod:'outdoor',plantCount:100}},
    {name:'Health OK',path:'/health'},{name:'Version OK',path:'/version'},
    {name:'Standards OK',path:'/standards'},{name:'Plants OK',path:'/plants'},
    {name:'Pricing OK',path:'/pricing/fees'},{name:'Master data OK',path:'/master-data'},
  ]},
  {key:'B05',name:'Rate Limit & Throttling',icon:'🚦',cat:'Backend',steps:[
    {name:'Req 1',path:'/health'},{name:'Req 2',path:'/health'},{name:'Req 3',path:'/health'},
    {name:'Req 4',path:'/health'},{name:'Req 5',path:'/health'},{name:'Req 6',path:'/standards'},
    {name:'Req 7',path:'/standards'},{name:'Req 8',path:'/plants'},{name:'Req 9',path:'/plants'},
    {name:'Req 10',path:'/master-data'},{name:'Req 11',path:'/pricing/fees'},
    {name:'All passed',path:'/health'},
  ]},
  {key:'B06',name:'Pricing & Calculation API',icon:'💲',cat:'Backend',steps:[
    {name:'Fee schedule',path:'/pricing/fees'},
    {name:'Calc outdoor',method:'POST',path:'/pricing/calculate',body:{plantCount:100,area:5,cultivationMethod:'outdoor'}},
    {name:'Calc indoor',method:'POST',path:'/pricing/calculate',body:{plantCount:50,area:2,cultivationMethod:'indoor'}},
    {name:'Calc greenhouse',method:'POST',path:'/pricing/calculate',body:{plantCount:200,area:10,cultivationMethod:'greenhouse'}},
    {name:'Phase 1 invoice',path:'/pricing/phase1-invoice'},
    {name:'Phase 2 invoice',path:'/pricing/phase2-invoice'},
    {name:'QR pricing',path:'/master-data/qr-pricing'},
    {name:'Master fees',path:'/master-data/fees'},
    {name:'Purposes',path:'/master-data/purposes'},
    {name:'Calc large',method:'POST',path:'/pricing/calculate',body:{plantCount:10000,area:100,cultivationMethod:'outdoor'}},
    {name:'Calc small',method:'POST',path:'/pricing/calculate',body:{plantCount:1,area:1,cultivationMethod:'outdoor'}},
    {name:'Calc mid',method:'POST',path:'/pricing/calculate',body:{plantCount:500,area:25,cultivationMethod:'outdoor'}},
  ]},
  {key:'B07',name:'Pagination & Sorting',icon:'📑',cat:'Backend',steps:[
    {name:'Standards list',path:'/standards'},{name:'Plants list',path:'/plants'},
    {name:'Locations list',path:'/master-data/locations'},{name:'Master data',path:'/master-data'},
    {name:'Audit trail',path:'/audit'},{name:'Audit stats',path:'/audit/stats'},
    {name:'GACP categories',path:'/cultivation-config/gacp-categories'},
    {name:'Soil types',path:'/cultivation-config/soil-types'},
    {name:'Cultivation methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Pricing fees',path:'/pricing/fees'},{name:'Health check',path:'/health'},
  ]},
  {key:'B08',name:'Search & Filter API',icon:'🔎',cat:'Backend',steps:[
    {name:'Standards search',path:'/standards?search=GACP'},
    {name:'Plants search',path:'/plants?search=herb'},
    {name:'Standards all',path:'/standards'},{name:'Plants all',path:'/plants'},
    {name:'Locations',path:'/master-data/locations'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Soil types',path:'/cultivation-config/soil-types'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'QR pricing',path:'/master-data/qr-pricing'},
    {name:'Fees',path:'/master-data/fees'},
    {name:'Purposes',path:'/master-data/purposes'},
    {name:'Full config',path:'/cultivation-config/full-config'},
  ]},
  {key:'B09',name:'Notification & Audit API',icon:'🔔',cat:'Backend',steps:[
    {name:'Audit trail',path:'/audit'},{name:'Audit stats',path:'/audit/stats'},
    {name:'Health check',path:'/health'},{name:'Version',path:'/version'},
    {name:'Metrics',path:'/metrics'},{name:'Standards',path:'/standards'},
    {name:'Plants',path:'/plants'},{name:'Master data',path:'/master-data'},
    {name:'Categories',path:'/cultivation-config/gacp-categories'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Pricing',path:'/pricing/fees'},{name:'Locations',path:'/master-data/locations'},
  ]},
  {key:'B10',name:'Audit Trail API',icon:'📋',cat:'Backend',steps:[
    {name:'Audit log',path:'/audit'},{name:'Audit stats',path:'/audit/stats'},
    {name:'Health ok',path:'/health'},{name:'DB status',path:'/health',field:'dbStatus.status'},
    {name:'Version',path:'/version',field:'version'},
    {name:'Metrics',path:'/metrics'},{name:'Standards count',path:'/standards'},
    {name:'Plants count',path:'/plants'},{name:'Locations count',path:'/master-data/locations'},
    {name:'Master data',path:'/master-data'},{name:'Fees',path:'/master-data/fees'},
    {name:'Full config',path:'/cultivation-config/full-config'},
  ]},
  {key:'B11',name:'Report & Export API',icon:'📊',cat:'Backend',steps:[
    {name:'Metrics report',path:'/metrics'},{name:'Audit stats',path:'/audit/stats'},
    {name:'Audit log',path:'/audit'},{name:'Health report',path:'/health'},
    {name:'Version info',path:'/version'},{name:'Standards data',path:'/standards'},
    {name:'Plants data',path:'/plants'},{name:'Pricing data',path:'/pricing/fees'},
    {name:'Locations data',path:'/master-data/locations'},
    {name:'Categories data',path:'/cultivation-config/gacp-categories'},
    {name:'Methods data',path:'/cultivation-config/cultivation-methods'},
    {name:'Full config',path:'/cultivation-config/full-config'},
  ]},
  {key:'B12',name:'Config & System API',icon:'⚙️',cat:'Backend',steps:[
    {name:'Document slots',path:'/config/document-slots'},
    {name:'Full cultivation config',path:'/cultivation-config/full-config'},
    {name:'GACP categories',path:'/cultivation-config/gacp-categories'},
    {name:'Soil types',path:'/cultivation-config/soil-types'},
    {name:'Cultivation methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Step 1 reqs',path:'/cultivation-config/step-requirements/1'},
    {name:'Step 5 reqs',path:'/cultivation-config/step-requirements/5'},
    {name:'Step 10 reqs',path:'/cultivation-config/step-requirements/10'},
    {name:'Standards',path:'/standards'},{name:'Plants',path:'/plants'},
    {name:'Master data',path:'/master-data'},{name:'Health',path:'/health'},
  ]},
  {key:'B13',name:'Concurrent Stress',icon:'🔥',cat:'Backend',steps:[
    {name:'Concurrent 1',path:'/health'},{name:'Concurrent 2',path:'/health'},
    {name:'Concurrent 3',path:'/standards'},{name:'Concurrent 4',path:'/standards'},
    {name:'Concurrent 5',path:'/plants'},{name:'Concurrent 6',path:'/plants'},
    {name:'Concurrent 7',path:'/master-data'},{name:'Concurrent 8',path:'/master-data'},
    {name:'Concurrent 9',path:'/pricing/fees'},{name:'Concurrent 10',path:'/pricing/fees'},
    {name:'Concurrent 11',path:'/audit'},{name:'Concurrent 12',path:'/metrics'},
  ]},
  {key:'B14',name:'API Response Time',icon:'⏱️',cat:'Backend',steps:[
    {name:'Health <3s',path:'/health'},{name:'Version <3s',path:'/version'},
    {name:'Standards <3s',path:'/standards'},{name:'Plants <3s',path:'/plants'},
    {name:'Master data <3s',path:'/master-data'},{name:'Locations <3s',path:'/master-data/locations'},
    {name:'Pricing <3s',path:'/pricing/fees'},{name:'Categories <3s',path:'/cultivation-config/gacp-categories'},
    {name:'Full config <3s',path:'/cultivation-config/full-config'},
    {name:'Audit <3s',path:'/audit'},{name:'Metrics <3s',path:'/metrics'},
    {name:'Audit stats <3s',path:'/audit/stats'},
  ]},
  {key:'B15',name:'Data Integrity API',icon:'🔐',cat:'Backend',steps:[
    {name:'Standards data',path:'/standards'},{name:'Plants data',path:'/plants'},
    {name:'Locations data',path:'/master-data/locations'},{name:'Fees data',path:'/master-data/fees'},
    {name:'QR pricing',path:'/master-data/qr-pricing'},{name:'Purposes',path:'/master-data/purposes'},
    {name:'GACP cats',path:'/cultivation-config/gacp-categories'},
    {name:'Soil types',path:'/cultivation-config/soil-types'},
    {name:'Methods',path:'/cultivation-config/cultivation-methods'},
    {name:'Full config',path:'/cultivation-config/full-config'},
    {name:'Doc slots',path:'/config/document-slots'},
    {name:'Health check',path:'/health'},
  ]},
];
