'use strict';

/**
 * A fingerprint of what a photograph LOOKS LIKE, not of its bytes.
 *
 * WHY THIS EXISTS
 *   Onsite evidence is counted by distinct SHA-256 of the file bytes, which makes the
 *   minimum-photo rule mean "N different files". An adversarial review on 2026-08-26 showed
 *   what that buys and what it does not: one real photograph from the G4 walk, re-saved by
 *   sharp at qualities 88/87/86/85 plus one copy with a single scan byte flipped, produced
 *   FIVE distinct SHA-256 digests, passed the upload door five times, and satisfied a
 *   minimum of five. Re-encoding also strips EXIF for free, so the copies looked cleaner
 *   than the original.
 *
 *   A cryptographic hash is built to change completely when one bit changes. That property
 *   is exactly what makes it useless for "is this the same photograph?".
 *
 * WHAT THIS IS, AND WHAT IT IS FOR
 *   dHash (difference hash): greyscale, resize to 9x8, and emit one bit per adjacent pixel
 *   pair — 1 when the left pixel is brighter than the right. 64 bits describing the
 *   direction of brightness change across the frame, which is a property of the SCENE and
 *   survives re-encoding, resizing and modest brightness or contrast changes. Two images are
 *   compared by Hamming distance: how many of the 64 bits differ.
 *
 *   This belongs to the same family as the robust hashes the industry uses for exactly this
 *   job — Microsoft's PhotoDNA, Google's CSAI Match — which every large platform runs to
 *   match images that have been re-saved, resized or lightly cropped.
 *
 * THE RULE THAT COMES WITH IT, AND IT IS NOT OPTIONAL
 *   A perceptual hash FLAGS FOR A HUMAN. It must never auto-reject evidence.
 *
 *   Every platform that runs one works this way: Google Photos clusters similar shots and
 *   lets you decide; PhotoDNA sends a match to a human moderator; an insurance adjuster's
 *   near-duplicate report goes to a supervisor. The reason is structural, not timid. An
 *   auditor photographing the same shed twice from the same doorway legitimately produces
 *   near-identical frames, so a threshold tight enough to catch deliberate reuse also
 *   catches honest work — while anyone actually trying only has to change the angle. Set it
 *   to refuse and you punish the careful and wave through the determined.
 *
 * WHAT IT DOES NOT CATCH, stated plainly so nobody assumes otherwise:
 *   - a different photograph of the same subject taken two seconds later — that is a
 *     different image and SHOULD score as one;
 *   - a heavy crop, a large rotation, or a mirror flip (dHash is not rotation-invariant);
 *   - a photograph of a printed photograph.
 *   Provenance is what closes those: capture in-app, bind to the visit's time and place, and
 *   eventually sign at the shutter (C2PA / hardware attestation). This is one layer.
 */

const sharp = require('sharp');

/** Columns sampled per row. 9 columns give 8 adjacent pairs, so 8 rows x 8 bits = 64. */
const HASH_WIDTH = 9;
const HASH_HEIGHT = 8;
const HASH_BITS = (HASH_WIDTH - 1) * HASH_HEIGHT;

/**
 * Bits that may differ before two images are worth showing a human side by side.
 *
 * PROVISIONAL, and the measurements below say exactly how provisional. Nothing is refused
 * on it; it only decides what gets highlighted in a report.
 *
 * WHAT WAS MEASURED (2026-08-26, this module against real runs):
 *
 *   Same image, transformed — the attack the adversarial review actually used:
 *     JPEG q95/q88/q85/q75/q60 re-encode ....... 1-7 bits
 *     resize to half width ..................... 7 bits
 *     one scan byte flipped .................... 2 bits
 *   Genuinely different images (control shapes: white circle on black, black rectangle on
 *   white, a left-to-right gradient):
 *     between any two of them .................. 14-25 bits
 *     one of them re-encoded at q55 ............ 0 bits
 *     one of them resized to 200px ............. 3 bits
 *
 *   So on content that genuinely differs, the two populations sit 3 vs 14 — a real gap, and
 *   10 sits inside it. The implementation is doing its job.
 *
 * WHAT COULD NOT BE MEASURED, and this is the part that matters:
 *   This repo has no real farm photographs. The five images under
 *   evidence/g4-rebuild-2026-08-25/a07 look like a photo set but are FIXTURES generated by
 *   scripts/g4/make-photo-fixture.js — labelled frames sharing one layout and differing
 *   mostly in their Thai caption. Run against them, "different" photos score 8-11 bits while
 *   re-encodes score 1-7, and the populations overlap almost completely.
 *
 *   That is not a flaw in the hash. Those images ARE nearly identical; the hash says so
 *   correctly. It means our only photo set cannot calibrate this number, and an earlier
 *   draft of this comment claimed a 0-2 versus 20+ separation that the measurement then
 *   contradicted.
 *
 * SO: treat 10 as a starting point for HIGHLIGHTING, re-derive it the first time a real
 * audit's photographs exist, and read the distance itself rather than the boolean wherever
 * a human is going to look.
 */
const NEAR_DUPLICATE_MAX_DISTANCE = 10;

/**
 * @param {Buffer} buffer raw image bytes
 * @returns {Promise<string>} 16 lower-case hex characters (64 bits), or throws if the bytes
 *   are not a decodable image — the caller decides what an undecodable file means, and for
 *   evidence that decision is "refuse", made at the upload door, not here.
 */
async function perceptualHash(buffer) {
    if (!Buffer.isBuffer(buffer) || buffer.length === 0) {
        throw new TypeError('perceptualHash: a non-empty Buffer is required');
    }

    // `raw()` after greyscale gives one byte per pixel in row-major order. `fit: 'fill'`
    // ignores aspect ratio on purpose: two crops of one scene should still line up column to
    // column, and preserving the ratio would shift every column and destroy the comparison.
    const pixels = await sharp(buffer)
        .greyscale()
        .resize(HASH_WIDTH, HASH_HEIGHT, { fit: 'fill' })
        .raw()
        .toBuffer();

    if (pixels.length !== HASH_WIDTH * HASH_HEIGHT) {
        throw new Error(
            `perceptualHash: expected ${HASH_WIDTH * HASH_HEIGHT} greyscale samples, got ${pixels.length}`,
        );
    }

    let bits = '';
    for (let row = 0; row < HASH_HEIGHT; row += 1) {
        for (let col = 0; col < HASH_WIDTH - 1; col += 1) {
            const left = pixels[(row * HASH_WIDTH) + col];
            const right = pixels[(row * HASH_WIDTH) + col + 1];
            bits += left > right ? '1' : '0';
        }
    }

    // Fixed-width hex so two hashes are always the same length and can be compared by index.
    let hex = '';
    for (let i = 0; i < bits.length; i += 4) {
        hex += parseInt(bits.slice(i, i + 4), 2).toString(16);
    }
    return hex;
}

/**
 * How many of the 64 bits differ. 0 means indistinguishable at this resolution.
 *
 * @param {string} a 16 hex characters
 * @param {string} b 16 hex characters
 * @returns {number} 0..64
 */
function hammingDistance(a, b) {
    const left = String(a || '').trim().toLowerCase();
    const right = String(b || '').trim().toLowerCase();
    if (left.length !== right.length || left.length === 0) {
        throw new TypeError('hammingDistance: two hashes of equal, non-zero length are required');
    }
    // Validated BEFORE the XOR, and that ordering is the whole point: parseInt('z', 16) is
    // NaN, but JavaScript's bitwise operators coerce NaN to 0, so `NaN ^ 0` is 0 and a
    // Number.isNaN check placed after the XOR can never fire. An earlier draft did exactly
    // that and reported two garbage strings as a perfect match — distance 0, the answer that
    // means "identical photograph".
    if (!/^[0-9a-f]+$/.test(left) || !/^[0-9a-f]+$/.test(right)) {
        throw new TypeError('hammingDistance: hashes must be hexadecimal');
    }

    let distance = 0;
    for (let i = 0; i < left.length; i += 1) {
        // Kernighan: clear the lowest set bit until none remain.
        let value = parseInt(left[i], 16) ^ parseInt(right[i], 16);
        while (value) { value &= value - 1; distance += 1; }
    }
    return distance;
}

/**
 * Is `b` near enough to `a` to be worth a human's attention?
 *
 * Deliberately named for what it means rather than for an action, because it does not
 * authorise one: the answer belongs on a screen a reviewing officer reads, never in an
 * `if` that refuses an upload.
 */
function isNearDuplicate(a, b, maxDistance = NEAR_DUPLICATE_MAX_DISTANCE) {
    return hammingDistance(a, b) <= maxDistance;
}

module.exports = {
    perceptualHash,
    hammingDistance,
    isNearDuplicate,
    NEAR_DUPLICATE_MAX_DISTANCE,
    HASH_BITS,
};
