'use client';

/**
 * The sign that gets stapled to a post.
 *
 * มกษ. 3502-2561 ข้อ 8(1) asks for a recorded plot code; Layer 1 minted one and put it on
 * Plot.plotCode. This file is where that column stops being a column: it is printed on
 * ordinary paper by an ordinary printer, nailed up at the edge of the plot, and left
 * outdoors for a season.
 *
 * Everything here answers to that. The sign is laid out for a printer, not for a screen —
 * black on white, one plot per page, and no colour that carries meaning, because the farmer
 * printing this at the district office is printing in greyscale whether they meant to or
 * not.
 *
 * The QR is generated by the caller (client-view.tsx) at error-correction level H with a
 * wide quiet zone. This component only places it, and places the code in large characters
 * underneath — that pairing is the whole point. A weathered, split, mud-splashed label stops
 * scanning long before it stops being readable, and when it does the farmer reads the code
 * down a phone. A sign carrying only a QR is a sign with one point of failure.
 *
 * A revoked sign reprints with the SAME code. The chain runs package -> lot -> harvest ->
 * cycle -> plot -> certificate; minting a fresh code on reprint would cut the last link and
 * orphan every record already written against the old one. Revocation retires a piece of
 * paper, not a plot.
 */

import { formatThaiDate } from '@/lib/format/thai-date';

export type PlotSign = {
  plotCode: string;
  plotName: string;
  farmName: string;
  /** PNG data URL, or null when the QR could not be built — the code still prints. */
  qrDataUrl: string | null;
  /** ISO timestamp when the previous sign was revoked; null for a first printing. */
  revokedAt?: string | null;
};

/**
 * `print:` variants below are deliberately absolute (white paper, black ink) rather than
 * token-driven: the tokens flip with the viewer's theme, and a farmer who printed the sign
 * with dark mode on would otherwise get a page of solid ink. On screen the sheet still uses
 * `bg-card` / `text-foreground` so it reads correctly in both themes.
 */
function PlotSignCard({ sign }: { sign: PlotSign }) {
  const revoked = Boolean(sign.revokedAt);

  return (
    <article
      data-plot-sign={sign.plotCode}
      className="break-inside-avoid break-after-page rounded-lg border-2 border-foreground bg-card p-8 text-center text-card-foreground last:break-after-auto print:rounded-none print:border-black print:bg-white print:text-black"
    >
      <p className="text-2xl font-bold">{sign.plotName}</p>
      <p className="mt-1 text-lg text-muted-foreground print:text-black">{sign.farmName}</p>

      {revoked ? (
        <p className="mt-4 text-base font-bold">
          พิมพ์ใหม่แทนป้ายเดิม รหัสแปลงเดิม ยกเลิกเมื่อ {formatThaiDate(sign.revokedAt)}
        </p>
      ) : null}

      {/* The white plate is the QR's quiet zone. It is drawn here rather than left to the
          module margin so the border of the sign can never crowd the finder patterns. */}
      <div className="mx-auto mt-6 w-fit rounded-lg bg-white p-6 print:rounded-none">
        {sign.qrDataUrl ? (
          // eslint-disable-next-line @next/next/no-img-element -- data: URL QR; next/image cannot optimise inline data URLs and rewrites break print
          <img
            src={sign.qrDataUrl}
            alt={`QR รหัสแปลง ${sign.plotCode}`}
            width={320}
            height={320}
            className="block h-[320px] w-[320px]"
          />
        ) : (
          <p className="w-[320px] text-base font-bold text-black">
            สร้างภาพ QR ไม่สำเร็จ พิมพ์ป้ายนี้ได้และใช้รหัสแปลงด้านล่างแทน
          </p>
        )}
      </div>

      <p className="mt-6 text-sm text-muted-foreground print:text-black">รหัสแปลง</p>
      {/* Latin-only, so uppercase + tracking are allowed here (thai-ui-copy rule covers
          Thai glyphs). Wide tracking is what makes the groups readable at arm's length. */}
      <p
        data-sign-code={sign.plotCode}
        className="mt-1 font-mono text-4xl font-bold uppercase tracking-wider"
      >
        {sign.plotCode}
      </p>

      <p className="mt-6 text-base">สแกนเพื่อบันทึกกิจกรรมของแปลงนี้</p>
      <p className="mt-1 text-sm text-muted-foreground print:text-black">
        ป้ายนี้อยู่กับแปลงถาวร ใช้ได้ทุกรอบปลูก ไม่ต้องพิมพ์ใหม่เมื่อขึ้นรอบใหม่
      </p>
    </article>
  );
}

export function PlotSignSheet({ signs }: { signs: PlotSign[] }) {
  return (
    <div className="space-y-8 print:space-y-0">
      {signs.map((sign) => (
        <PlotSignCard key={sign.plotCode} sign={sign} />
      ))}
    </div>
  );
}
