/**
 * Visual regression baseline — public pages.
 *
 * Why: Pass 1-5 of the design effort hardened many specific surfaces
 * (button rows, table overflow, form labels, Thai validators). Without a
 * visual regression net, the next bug is one un-reviewed CSS edit away.
 * This spec captures pixel snapshots of the four public pages that don't
 * need auth, so any incidental visual change in subsequent passes shows
 * up as a CI diff.
 *
 * Workflow:
 *   - First time per page (or after an intentional redesign):
 *       pnpm --filter web-app exec playwright test e2e/visual --update-snapshots
 *     Commit the resulting `*.png` files alongside the spec file.
 *
 *   - On every later PR:
 *       pnpm --filter web-app exec playwright test e2e/visual
 *     Fails if any pixel diff exceeds the per-test threshold.
 *
 * Defaults:
 *   - Run against `process.env.E2E_BASE_URL` (defaults to `http://localhost`,
 *     same as the rest of the e2e suite). Operator can point at production
 *     by setting `E2E_BASE_URL=https://gacpth.com`.
 *   - Animations disabled to make screenshots deterministic.
 *   - Per-test threshold 1% — generous enough to absorb sub-pixel font
 *     antialiasing differences across CI runners; tight enough that real
 *     layout shifts surface immediately.
 *
 * NOTE: snapshot baselines are NOT committed by this PR — the operator
 * runs --update-snapshots once against the canonical environment, reviews
 * the captured PNGs, and commits them in a follow-up. The test is marked
 * `.fixme` here until then so CI doesn't block on a missing baseline.
 */

import { test, expect } from '@playwright/test';

// All four routes are SSR-rendered + auth-free. They cover login chrome
// (auth/health/login), legal copy (terms, privacy), and the accessibility
// statement we ship as part of the gov-design Phase A5 commitment.
const PUBLIC_PAGES = [
  { path: '/auth/health/login', name: 'health-login' },
  { path: '/accessibility',     name: 'accessibility-statement' },
  { path: '/terms',             name: 'terms-of-service' },
  { path: '/privacy',           name: 'privacy-policy' },
] as const;

test.describe('Visual regression — public pages', () => {
  for (const { path, name } of PUBLIC_PAGES) {
    // Mark as fixme until baseline snapshots are generated by the operator
    // running `--update-snapshots`. Once the baseline PNGs land in the
    // `__screenshots__` folder, drop the .fixme to enable the gate.
    test.fixme(`${name} matches snapshot`, async ({ page }) => {
      await page.goto(path, { waitUntil: 'networkidle' });

      // Disable CSS animations + transitions so the screenshot is
      // deterministic. Without this, the animated check-in pulse on
      // login button (or similar) makes every run differ.
      await page.addStyleTag({
        content: `*, *::before, *::after {
          animation-duration: 0s !important;
          animation-delay: 0s !important;
          transition-duration: 0s !important;
          transition-delay: 0s !important;
        }`,
      });

      // Wait one extra rAF for the style injection to settle.
      await page.evaluate(() => new Promise((r) => requestAnimationFrame(() => r(null))));

      await expect(page).toHaveScreenshot(`${name}.png`, {
        // Full-page so layout shifts in the footer / below the fold are caught.
        fullPage: true,
        // ~1% pixel tolerance — absorb font-AA noise without missing real
        // layout regression.
        maxDiffPixelRatio: 0.01,
        // Animations are disabled above; this is belt-and-braces for any
        // animation we missed (e.g. iframe content).
        animations: 'disabled',
      });
    });
  }
});
